// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZnw7VgX9oPY2fpJDe2JIOVm8ydvujH0k',
    appId: '1:494113639481:web:32ef3cec6cba44e6fb11e8',
    messagingSenderId: '494113639481',
    projectId: 'n-safety-app',
    authDomain: 'n-safety-app.firebaseapp.com',
    databaseURL: 'https://n-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n-safety-app.firebasestorage.app',
    measurementId: 'G-C1CLTJCGTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK_xzS8-cplQdCJDpyhbNfA8EW7SQGdik',
    appId: '1:494113639481:android:a2b01623ad341350fb11e8',
    messagingSenderId: '494113639481',
    projectId: 'n-safety-app',
    databaseURL: 'https://n-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n-safety-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY2_ompAlA8aMf7TWEsmSkeduuEoO-shM',
    appId: '1:494113639481:ios:c4c85d24665f1d2bfb11e8',
    messagingSenderId: '494113639481',
    projectId: 'n-safety-app',
    databaseURL: 'https://n-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n-safety-app.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY2_ompAlA8aMf7TWEsmSkeduuEoO-shM',
    appId: '1:494113639481:ios:c4c85d24665f1d2bfb11e8',
    messagingSenderId: '494113639481',
    projectId: 'n-safety-app',
    databaseURL: 'https://n-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n-safety-app.firebasestorage.app',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZnw7VgX9oPY2fpJDe2JIOVm8ydvujH0k',
    appId: '1:494113639481:web:782e186a65b35fc4fb11e8',
    messagingSenderId: '494113639481',
    projectId: 'n-safety-app',
    authDomain: 'n-safety-app.firebaseapp.com',
    databaseURL: 'https://n-safety-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'n-safety-app.firebasestorage.app',
    measurementId: 'G-95514FZ4JX',
  );
}
